# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Changelog

author: liblaf

description: Changelog

inputs:
  # ref: <https://github.com/orhun/git-cliff-action>
  config:
    description: Path of the configuration file.
    required: false
  args:
    description: Arguments to pass to git-cliff.
    required: false
    default: --verbose
  token:
    description: The GitHub API token used to get git-cliff release information via the GitHub API to avoid rate limits.
    required: false
    default: ${{ github.token }}

  output:
    description: Output file.
    required: false
    default: ${{ runner.temp }}/CHANGELOG.md
  repository:
    description: The owner and repository name. For example, `octocat/Hello-World`.
    required: false
    default: ${{ github.repository }}

outputs:
  changelog:
    description: Output file that contains the generated changelog.
    value: ${{ steps.cliff.outputs.changelog }}
  content:
    description: Content of the changelog.
    value: ${{ steps.output.outputs.content }}
  version:
    description: Version of the latest release.
    value: ${{ steps.cliff.outputs.version }}

runs:
  using: composite
  steps:
    - id: config
      name: Find Config
      run: |-
        if [[ -f '${{ inputs.config }}' ]]; then
          printf 'config=%s\n' '${{ inputs.config }}' >> "$GITHUB_OUTPUT"
        else
          printf 'config=%s\n' '${{ github.action_path }}/cliff.toml' >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - id: cliff
      name: Generate Changelog
      uses: orhun/git-cliff-action@v4
      with:
        config: ${{ steps.config.outputs.config }}
        args: ${{ inputs.args }}
        github_token: ${{ inputs.token }}
      env:
        DEBUG: ${{ runner.debug }}
        GITHUB_REPO: ${{ inputs.repository }}
        GITHUB_TOKEN: ${{ inputs.token }}
        OUTPUT: ${{ inputs.output }}
    - name: Ensure Output File Exists
      run: |-
        if [[ ! -f '${{ inputs.output }}' ]]; then
          touch '${{ inputs.output }}'
        fi
      shell: bash
    - name: Prettier
      run: npx prettier --write '${{ inputs.output }}'
      shell: bash
    - id: output
      name: Set Output
      run: |-
        delimiter="$(uuidgen)"
        {
          printf 'content<<%s\n' "$delimiter"
          cat '${{ inputs.output }}'
          printf '%s\n' "$delimiter"
        } >> "$GITHUB_OUTPUT"
      shell: bash
