name: Custom / Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]*"
  workflow_dispatch:

env:
  TARGET_REPOSITORY: ${{ github.repository_owner }}/actions

concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - name: Install Dependencies
        run: |-
          bun install
          bun pm bin >> "$GITHUB_PATH"
      - name: Build
        run: bun run build
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      # JamesIves/github-pages-deploy-action requires checkout
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Download Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: dist
          path: dist
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Deploy to main
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: main
          folder: dist
          repository-name: ${{ env.TARGET_REPOSITORY }}
          single-commit: true
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        name: Deploy to ${{ github.ref_name }}
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: release/${{ github.ref_name }}
          folder: dist
          repository-name: ${{ env.TARGET_REPOSITORY }}
          single-commit: true

  tag:
    name: Tag
    needs:
      - deploy
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: ${{ env.TARGET_REPOSITORY }}
          ref: release/${{ github.ref_name }}
          token: ${{ secrets.DEPLOY_TOKEN }}
      - name: Tag
        run: |-
          # Using `echo -n` to avoid extra newline from process substitution `<<<`
          readarray -d '.' -t parts < <(echo -n '${{ github.ref_name }}')
          tag=''
          for part in "${parts[@]}"; do
            tag="${tag:+"$tag."}$part"
            git tag --force "$tag"
            git push --force origin tag "$tag"
          done
